--CREANDO USUARIOS
CREATE USER APEX_DEV
IDENTIFIED BY "123456Abcdef"
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON DATA;

- 3. PRIVILEGIOS BÁSICOS DE CONEXIÓN
GRANT CONNECT TO APEX_DEV;
GRANT RESOURCE TO APEX_DEV;

-- 4. PRIVILEGIOS DE CREACIÓN DE OBJETOS
GRANT CREATE SESSION TO APEX_DEV;
GRANT CREATE TABLE TO APEX_DEV;
GRANT CREATE VIEW TO APEX_DEV;
GRANT CREATE SEQUENCE TO APEX_DEV;
GRANT CREATE PROCEDURE TO  APEX_DEV;
GRANT CREATE TRIGGER TO  APEX_DEV;
GRANT CREATE SYNONYM TO  APEX_DEV;
GRANT CREATE TYPE TO  APEX_DEV;
GRANT CREATE MATERIALIZED VIEW TO  APEX_DEV;

-- 5. PRIVILEGIOS PARA DESARROLLO
GRANT ALTER SESSION TO  APEX_DEV;
GRANT CREATE JOB TO  APEX_DEV;
GRANT CREATE DATABASE LINK TO  APEX_DEV;

-- 6. PRIVILEGIOS PARA DEBUGGING
GRANT DEBUG CONNECT SESSION TO  APEX_DEV;
GRANT DEBUG ANY PROCEDURE TO  APEX_DEV;

-- 7. VERIFICAR PRIVILEGIOS OTORGADOS
SELECT * FROM dba_sys_privs WHERE grantee = 'APEX_DEV' ORDER BY privilege;

-- 8. VERIFICAR ROLES OTORGADOS
SELECT * FROM dba_role_privs WHERE grantee = 'APEX_DEV';





